### ISSUE TITLE
Error cannot open FinalFont

### ISSUE THREAD

**Issue by ItzSyther** [fcolecumberri/Doddler_Bizarre_Adventure_in_the_Matriarchy#3]
So when trying to open xsystem35.exe I am prompted with this (installing the font the usual way didnt work and placing it within the same folder as .exe did nothing)
![image (13)](https://github.com/user-attachments/assets/e3f2f9ed-fbc1-4538-bade-fa41ceacba22)

**Comment by ItzSyther** [comment]
I was able to fix it by removing .xsys35rc

**Comment by fcolecumberri** [comment]
Ok, that's weird because `FinalFont/FinalFont.ttf` is in the release.
