### ISSUE TITLE
[help] Unable to install/extract all Daiakuji's files with Windows/Android

### ISSUE THREAD

**Issue by KaroNiko** [fcolecumberri/Doddler_Bizarre_Adventure_in_the_Matriarchy#4]
HI. First of all, I thank the author of this translation project regarding one of Alicesoft's indisputable tactical-rpg "gems"; I no longer hoped for an english translation. I hope he will receive the help and support of other users.

I have had a copy of Daiakuji for a long time (two CD images) but I have never managed to install it. I would like to help test the english patch, playing this game on android tablet via xsystem35-sdl2. 

1) I tried to extract the necessary files on tablet using the Iso-extractor application, but I have problems with the second CD; the main file results in 0 bytes in size (a sort of anti-piracy protection?) and the ideograms are replaced by meaningless symbols; 

2) If I install the game on Windows 7 PC (via daemon tool launched with applocale), the installation doesn't even start, and in any case even here the ideograms are replaced by random symbols and unrecognized. Do I really need to change the system language to japanese, as suggested by some sites? But in this way I would no longer understand anything about the interface and the various Windows options. 
Does anyone have a helpful tip? Or could you provide me with the necessary files somehow, if possible? 
Thanks for your attention.

**Comment by linakima** [comment]
1. Android guide 
https://github.com/kichikuou/xsystem35-sdl2?tab=readme-ov-file#android
2. Run your install .exe file through the locale emulator.
https://github.com/xupefei/Locale-Emulator

**Comment by KaroNiko** [comment]
As I specified in point 2), I have already tried with **applocale** without success. I will also try with this similar locale software but I'm afraid the result will be the same. Thanks anyway.

**Comment by KaroNiko** [comment]
Using the local emulator I managed to install the first disk on the PC, the ideograms of which are correctly recognized, but when during the installation I mount the second CD image (when requested by the installer), this is not recognized and is requested again. I'm afraid the Lite version of Daemon Tool is not enough; in fact, certain important options cannot be activated. The .ald file contained is recognized as 0 bytes, as already mentioned.

**Comment by fcolecumberri** [comment]
Ok, this weekend I will install a VM with windows and try to install the game from CDs and if I succeed I'll document the process, if not, I might ask kichikuou and Nunuhara.

**Comment by KaroNiko** [comment]
Thanks chief, I appreciate your interest, but I'm afraid I won't be able to resolve the issue unless I get that damned 2nd disk audio file through other ways, or waiting for the pre-patched game to be uploaded on that well-known "eroge" site. 🤷

**Comment by fcolecumberri** [comment]
This is not about you, this is about the project, you found a issue that I didn't knew the project have (Thanks for sharing it), installing the game is not so straight forward on windows. This issue is about you and about everyone that will come after you to have a documented way to play the game. I'll try my best.

**Comment by linakima** [comment]
I found the game image on two discs.
The first disc contains the game files. It is easy installed using the locale emulator.
The second disk contains video and music. It does not need to be installed, just mount it in a disc drive and run the installed game using the .exe file through the locale emulator.

大悪司SB.ALD is empty. I think this is for a protection. The system simply checks that the file exists.

**Comment by KaroNiko** [comment]
Nah, 大悪司SB.ALD appears to be 0 bytes in size, but in reality it will be around 500 MB; this is the file that contains the game audio (I assume), and if I extract it via local emulator, it  always results of zero size. The other files contained in that 2nd disk are small and useless. This 大悪司SB.ALD is protected in some way and the actual size is not detected correctly, not even with Daemon Tool (virtual drive).
I have to extract this damn file, then copy all the other necessary files onto the android tablet, and launch the game via xsystem35-sdl2.

Sure, I underline that I speak not only for myself, but for anyone who has to face this same issue.

**Comment by linakima** [comment]
> Nah, 大悪司SB.ALD appears to be 0 bytes in size, but in reality it will be around 500 MB

Nope, it's a .wav files. Check it with the 7zip.
I'm not sure if this 2 CD version allowed the game to be fully unpacked. I think the second disc always had to be in the CD drive. I checked the digital version of the game and there is also a file 大悪司SB.ALD and it is empty. 

![wav](https://github.com/user-attachments/assets/ddca0922-f9c7-4b64-b24e-fd6f98ca00fb)

**Comment by KaroNiko** [comment]
Okay. Thanks for the clarification. For some absurd reason, using UltraIso, CDMage, Daemon Tool, I can't view those .wav files, but only some data files (plus that damn .ald file already mentioned) on the 2nd disc. 7zip can't even open the .img format file (it says it's not an archive). 

If things are as you say, all the .wav files should be extracted, converted to .mp3 format, inserted into a BGM folder, then creating a corresponding playlist.txt, to play on android devices via xsystem35-sdl2. 
I think this is easily done, but in my case I'm at a dead end, and I'm throwing in the towel for now. These absurd complications inexorably give me a painful headache; and after all, I'm a simple gamer, not a computer brainiac. 😅

**Comment by linakima** [comment]
> 7zip can't even open the .img format file (it says it's not an archive).

Hm, strange. My version is 22.01 x64 (2022-07-15). Maybe I installed some plugins and forgot about it.
All .wav files: https://pixeldrain.com/u/EUyM4zas

**Comment by KaroNiko** [comment]
Thanks, but I'm afraid that site cannot be reached from my country (Italy); Android Chrome tells me that the connection is not private, and my data could be stolen by malicious third parties. 🤷

**Comment by linakima** [comment]
google drive: https://drive.google.com/file/d/1X3In_dAnZvabCYygasnnfw5RviZZBECv/view?usp=drive_link

**Comment by KaroNiko** [comment]
Hey @Kichikuou, sorry to bother you here. 🙏 Is the folder structure of this game right? Do music files have to be sorted like this? As regards the data files, they do not all correspond to those indicated by the author of this translation project , perhaps because they derive from the CD version and not from the digital one? Who can say... And then there's that useless, empty .ald file, present in both versions. 🤔
Finally, the entire folder should be compressed into a zip archive and installed inside the xsystem35-sdl2 apk, right? 

![1725569752393](https://github.com/user-attachments/assets/ba555316-8b9b-4a96-8447-9cae15df6c5e)


Alas, for now this will be a problem, since unfortunately I just realized that I have no more space in the internal storage of my tablet, and I will have to sacrifice some titles to make room for it, which will be a long, painful and difficult choice, dammit. 😖

Well, for now I would just like confirmation that the structure of the game (folders, files and everything) is correct. Thank you.

**Comment by KaroNiko** [comment]
Okay. Since the person I mentioned didn't respond (notification not received?) I proceeded to install the game as described above. Well, it works perfectly, graphics and music, at least as far as I have reached (general map with the various regions). Also in this case, as with other titles, the exit button is not available on android; issue already brought to the attention of the author. 

So, for those interested, keep in mind that the .wav files must be converted into .mp3 format, inserted into a folder, then creating a playlist.txt containing the various tracks in order, all as in the previous photo. 

For now I have tried the game in the original language; then I will test the english patched version. 

EDIT: Now I have also tested the english translation, the initial dialogues up to the general map. Nice font, easily readable on android device. My knowledge of english is unfortunately very elementary, scholastic, but I still noticed various inconsistencies in the english text, sentences that apparently make little sense, japanese expressions reported verbatim but not translated with the corresponding english term. fragmented sentences disconnected from the context. 
In my opinion the text should be checked and corrected by someone fluent in both languages, or at least by a native english person who should check the text while playing, this by inserting and correcting the sentences in the right context. I'm obviously not up to the task, but I could report the most glaring and obvious errors.
 I hope I didn't come across as inappropriate or presumptuous.
Regards.

**Comment by KaroNiko** [comment]
@fcolecumberri , if you have already read what I wrote previously, as far as I'm concerned, you can close this issue; all the necessary files can be obtained from the two CD images. Apparently both the digital and disc versions (with the files modified with english text) are playable without problems on xsystem35-sdl2 (android version). 
Good luck for your translation project.

**Comment by fcolecumberri** [comment]
I will close it, thanks. However I still want to make more documentation about how to make it work on Windows.
